// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMzkPsumjlUNsdXj6wMTK-A5iINPv5UlI',
    appId: '1:337066927789:web:52c0ed944bf4a9e9e94824',
    messagingSenderId: '337066927789',
    projectId: 'chatapp-83ebb',
    authDomain: 'chatapp-83ebb.firebaseapp.com',
    storageBucket: 'chatapp-83ebb.appspot.com',
    measurementId: 'G-W2FGLRBH77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29JMxbt4ZSAAQ1jPyUvCqlCCN28Nlk7A',
    appId: '1:337066927789:android:75cdad9f497d500de94824',
    messagingSenderId: '337066927789',
    projectId: 'chatapp-83ebb',
    storageBucket: 'chatapp-83ebb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUhQnrkR3VqZKNeEPpxsSR-ve75i2li2c',
    appId: '1:337066927789:ios:3173989f0b2337d5e94824',
    messagingSenderId: '337066927789',
    projectId: 'chatapp-83ebb',
    storageBucket: 'chatapp-83ebb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUhQnrkR3VqZKNeEPpxsSR-ve75i2li2c',
    appId: '1:337066927789:ios:3173989f0b2337d5e94824',
    messagingSenderId: '337066927789',
    projectId: 'chatapp-83ebb',
    storageBucket: 'chatapp-83ebb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMzkPsumjlUNsdXj6wMTK-A5iINPv5UlI',
    appId: '1:337066927789:web:978ac3c57e69592de94824',
    messagingSenderId: '337066927789',
    projectId: 'chatapp-83ebb',
    authDomain: 'chatapp-83ebb.firebaseapp.com',
    storageBucket: 'chatapp-83ebb.appspot.com',
    measurementId: 'G-4MN4HNK5L6',
  );
}
